# Generated by Django 3.2.5 on 2021-07-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NonPrimaryADAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrimaryID', models.CharField(max_length=30)),
                ('SecondaryID', models.CharField(max_length=30)),
                ('FirstName', models.CharField(max_length=200)),
                ('Surname', models.CharField(max_length=200)),
                ('EmailAddress', models.EmailField(max_length=200)),
                ('JobTitle', models.CharField(max_length=200)),
                ('Department', models.CharField(max_length=200)),
                ('Company', models.CharField(max_length=200)),
                ('Manager', models.CharField(max_length=200)),
                ('ManagerID', models.CharField(max_length=30)),
                ('CreatedAt', models.DateField()),
            ],
        ),
    ]
